# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run_crawler:
    dir: src/crawler
    aliases: [rc]
    cmds:
      - go test
      - go run main.go
