# https://taskfile.dev

version: "3"

dotenv: [".env"]

vars:
  GREETING: Hello, World!

tasks:
  pp:
    dir: src/crawler
    cmds:
      - cat data.json | jq .
    silent: true

  run_crawler:
    dir: src/crawler
    aliases: [rc]
    cmds:
      - go test
      - time go run main.go
